// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

package cn.yase.grpc.proto;

public interface HelloResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hello.HelloResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string reply = 1;</code>
   */
  java.lang.String getReply();
  /**
   * <code>string reply = 1;</code>
   */
  com.google.protobuf.ByteString
      getReplyBytes();
}
